# fly.toml app configuration file generated for heroic-support on 2026-02-17T16:28:03-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'heroic-support'
primary_region = 'lax'

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
